# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|
  config.vm.box       = "centos6.3"
  config.vm.box_url   = "http://developer.nrel.gov/downloads/vagrant-boxes/CentOS-6.3-x86_64-v20130101.box"
  config.vm.host_name = "vagrant.private"

  # Basic manifest to bootstrap
  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = "../puppet/manifests"
    puppet.manifest_file  = "site.pp"
    puppet.module_path    = "../puppet/modules"
    puppet.options        = %w[ --verbose --debug ]
  end

  # Path to puppet manifests
  config.vm.share_folder "puppet", "/etc/puppet/shared", "../../vagrant-puppet"

  config.vm.network :hostonly, "192.168.33.10"
  config.vm.network :bridged
  # config.vm.forward_port 80, 8080
end
